### ISSUE TITLE
뭔가 동작하는 것이 안보이네요

### ISSUE THREAD

**Issue by hannut91** [CodeSoom/project-react-2-DavidYang2149#13]
지금 내가 앱으로 무엇을 할 수 있는지 잘 모르겠어요. 저장한 후에 무엇을 할 수 있나요?

**Comment by DavidYang2149** [comment]
우선은 레시피를 저장하는 것이 1차 목표입니다.
이 후 레시피 목록을 볼 수 있고 생산량 변경에 따라 레시피의 용량(g)을 변경하는 것을 목표로 두고 있습니다.

**Comment by DavidYang2149** [comment]
[레시피 목록](https://davidyang2149.github.io/project-react-2-DavidYang2149/#/) 작성 완료
